# Generated by Django 4.0.2 on 2022-03-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
